package com.example.wangchang.wda1150_xwk1151;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wangchang.wda1150_xwk1151.Been.TaskBeen;
import com.example.wangchang.wda1150_xwk1151.Been.AccountBeen;

import com.example.wangchang.wda1150_xwk1151.TaskBeenDao;
import com.example.wangchang.wda1150_xwk1151.AccountBeenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskBeenDaoConfig;
    private final DaoConfig accountBeenDaoConfig;

    private final TaskBeenDao taskBeenDao;
    private final AccountBeenDao accountBeenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskBeenDaoConfig = daoConfigMap.get(TaskBeenDao.class).clone();
        taskBeenDaoConfig.initIdentityScope(type);

        accountBeenDaoConfig = daoConfigMap.get(AccountBeenDao.class).clone();
        accountBeenDaoConfig.initIdentityScope(type);

        taskBeenDao = new TaskBeenDao(taskBeenDaoConfig, this);
        accountBeenDao = new AccountBeenDao(accountBeenDaoConfig, this);

        registerDao(TaskBeen.class, taskBeenDao);
        registerDao(AccountBeen.class, accountBeenDao);
    }
    
    public void clear() {
        taskBeenDaoConfig.clearIdentityScope();
        accountBeenDaoConfig.clearIdentityScope();
    }

    public TaskBeenDao getTaskBeenDao() {
        return taskBeenDao;
    }

    public AccountBeenDao getAccountBeenDao() {
        return accountBeenDao;
    }

}
